name: Test And Release

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests / OS ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.10", "3.11", "3.12","3.13"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - name: Install uv
        uses: astral-sh/setup-uv@main
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --all-extras --dev

      - name: Run tests
        run: uv run bash scripts/test.sh

      - name: Run linters
        run: uv run bash scripts/lint.sh

  semantic-release:
    name: Bump Version and Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          token: ${{ secrets.ATTICUS_PAT }}

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: pyproject.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          body:  ${{ steps.git-cliff.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# Reference
# 1. https://docs.astral.sh/uv/guides/integration/github/#syncing-and-running
# 2. https://github.com/Kludex/python-template/blob/main/.github/workflows/main.yml
# 3. https://commitizen-tools.github.io/commitizen/tutorials/github_actions/
# 4. https://git-cliff.org/docs/github-actions/git-cliff-action
